# Generated by Django 4.2.13 on 2024-06-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiStore',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, db_comment='店铺名称', max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'api_store',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApiGoods',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=64, unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('conver_image', models.CharField(blank=True, db_comment='封面图片', max_length=255, null=True)),
                ('introduction_media', models.JSONField(blank=True, db_comment='介绍图片', null=True)),
                ('specifications', models.JSONField(blank=True, db_comment='规格', null=True)),
                ('parameters', models.JSONField(blank=True, db_comment='商品参数', null=True)),
                ('service', models.JSONField(blank=True, db_comment='服务', null=True)),
                ('display_image', models.JSONField(blank=True, db_comment='展示图片', null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.apistore')),
            ],
            options={
                'db_table': 'api_goods',
                'managed': True,
            },
        ),
    ]
